#!/bin/bash
# This is a script that outputs a random number between 1 and 20...

# Output a random number between 1 and 20...
number=$(( $RANDOM % 20 + 1 ))

# Print the output to the standard output stream...
echo "You rolled a $number"